services:
  alison-db:
    image: postgres:16-alpine
    container_name: alison-db
    hostname: alison-db
    restart: unless-stopped
    ports:
      - 5431:5431
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=AlisonDB
    volumes:
      - ./alison-db-data:/var/lib/postgresql/data
    networks:
      - quickstack-platform-interconnect
    command: -p 5431
  alison-runner:
    container_name: alison-runner
    hostname: alison-runner
    image: alison-v3:latest
    restart: unless-stopped
    build:
      context: .
    depends_on:
      - alison-db
    networks:
      - quickstack-platform-interconnect

networks:
  quickstack-platform-interconnect:
    external: true